### ISSUE TITLE
Horrible Design

### ISSUE THREAD

**Issue by Laphatize** [jmblount/cliffside.github.io#4]
Dang, please fix the css.
<img width="1280" alt="screen shot 2018-02-22 at 7 06 34 pm" src="https://user-images.githubusercontent.com/23617187/36571249-bed2c382-1803-11e8-91f6-eeeea9a275ea.png">
I mean look at it, completely horrible.

**Comment by jmblount** [comment]
Soon TM

At least I didn't generate mine without not making it myself

**Comment by jmblount** [comment]
I'm currently experimenting with various color palettes right now, can be previewed via branch design-1-preview. Thank you!
